In [18]:
import warnings
warnings.filterwarnings('ignore')

In [19]:
import pandas as pd
import numpy as np
import plotly.express as px
import datetime as dt

In [20]:
df = pd.read_csv('/content/Unemployment in India.csv')

**This dataset contains the Unemployment rate in all Region in india.**

In [21]:
df.head()

Region         Date  Frequency   Estimated Unemployment Rate (%)  \
0  Andhra Pradesh   31-05-2019    Monthly                              3.65   
1  Andhra Pradesh   30-06-2019    Monthly                              3.05   
2  Andhra Pradesh   31-07-2019    Monthly                              3.75   
3  Andhra Pradesh   31-08-2019    Monthly                              3.32   
4  Andhra Pradesh   30-09-2019    Monthly                              5.17   

    Estimated Employed   Estimated Labour Participation Rate (%)   Area  
0           11999139.0                                     43.24  Rural  
1           11755881.0                                     42.05  Rural  
2           12086707.0                                     43.50  Rural  
3           12285693.0                                     43.97  Rural  
4           12256762.0                                     44.68  Rural

In [34]:
df.tail()

Region       Date Frequency  Estimated Unemployment Rate (%)  \
749  West Bengal 2020-02-29   Monthly                             7.55   
750  West Bengal 2020-03-31   Monthly                             6.67   
751  West Bengal 2020-04-30   Monthly                            15.63   
752  West Bengal 2020-05-31   Monthly                            15.22   
753  West Bengal 2020-06-30   Monthly                             9.86   

     Estimated Employed  Estimated Labour Participation Rate (%)   Area  
749          10871168.0                                    44.09  Urban  
750          10806105.0                                    43.34  Urban  
751           9299466.0                                    41.20  Urban  
752           9240903.0                                    40.67  Urban  
753           9088931.0                                    37.57  Urban

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 7 columns):
 #   Column                                    Non-Null Count  Dtype  
---  ------                                    --------------  -----  
 0   Region                                    740 non-null    object 
 1    Date                                     740 non-null    object 
 2    Frequency                                740 non-null    object 
 3    Estimated Unemployment Rate (%)          740 non-null    float64
 4    Estimated Employed                       740 non-null    float64
 5    Estimated Labour Participation Rate (%)  740 non-null    float64
 6   Area                                      740 non-null    object 
dtypes: float64(3), object(4)
memory usage: 42.1+ KB


In [23]:
df.isna().sum() / df.shape[0] * 100

Region                                      3.645833
 Date                                       3.645833
 Frequency                                  3.645833
 Estimated Unemployment Rate (%)            3.645833
 Estimated Employed                         3.645833
 Estimated Labour Participation Rate (%)    3.645833
Area                                        3.645833
dtype: float64

**Since the Null values are all less than 5%....i just have to drop them ....it won't affect our analysis**

In [28]:
df.dropna(inplace=True)

**EXPLORATORY DATA ANALYSIS**

In [29]:
df.shape

(740, 7)

**The rows has been reduced from 768 to 740**

In [33]:
df.describe()

Date  Estimated Unemployment Rate (%)  \
count                            740                       740.000000   
mean   2019-12-12 18:36:58.378378496                        11.787946   
min              2019-05-31 00:00:00                         0.000000   
25%              2019-08-31 00:00:00                         4.657500   
50%              2019-11-30 00:00:00                         8.350000   
75%              2020-03-31 00:00:00                        15.887500   
max              2020-06-30 00:00:00                        76.740000   
std                              NaN                        10.721298   

       Estimated Employed  Estimated Labour Participation Rate (%)  
count        7.400000e+02                               740.000000  
mean         7.204460e+06                                42.630122  
min          4.942000e+04                                13.330000  
25%          1.190404e+06                                38.062500  
50%          4.744178e+06                                41.160000  
75%          1.127549e+07                                45.505000  
max          4.577751e+07                                72.570000  
std          8.087988e+06                                 8.111094

In [27]:
from datetime import datetime
df[' Date'] = pd.to_datetime(df[' Date'])

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 7 columns):
 #   Column                                    Non-Null Count  Dtype         
---  ------                                    --------------  -----         
 0   Region                                    740 non-null    object        
 1    Date                                     740 non-null    datetime64[ns]
 2    Frequency                                740 non-null    object        
 3    Estimated Unemployment Rate (%)          740 non-null    float64       
 4    Estimated Employed                       740 non-null    float64       
 5    Estimated Labour Participation Rate (%)  740 non-null    float64       
 6   Area                                      740 non-null    object        
dtypes: datetime64[ns](1), float64(3), object(3)
memory usage: 42.1+ KB


In [30]:
df.rename(columns={' Date':'Date', ' Frequency':'Frequency', ' Estimated Unemployment Rate (%)':'Estimated Unemployment Rate (%)', ' Estimated Employed':'Estimated Employed', ' Estimated Labour Participation Rate (%)':'Estimated Labour Participation Rate (%)'},inplace=True)

In [31]:
df.select_dtypes(include='object').columns

Index(['Region', 'Frequency', 'Area'], dtype='object')

In [32]:
df.select_dtypes(include='number').columns

Index(['Estimated Unemployment Rate (%)', 'Estimated Employed',
       'Estimated Labour Participation Rate (%)'],
      dtype='object')

In [35]:
df['Estimated Employed'] = round(df['Estimated Employed']/1000000,2)

df.head()

Region       Date Frequency  Estimated Unemployment Rate (%)  \
0  Andhra Pradesh 2019-05-31   Monthly                             3.65   
1  Andhra Pradesh 2019-06-30   Monthly                             3.05   
2  Andhra Pradesh 2019-07-31   Monthly                             3.75   
3  Andhra Pradesh 2019-08-31   Monthly                             3.32   
4  Andhra Pradesh 2019-09-30   Monthly                             5.17   

   Estimated Employed  Estimated Labour Participation Rate (%)   Area  
0               12.00                                    43.24  Rural  
1               11.76                                    42.05  Rural  
2               12.09                                    43.50  Rural  
3               12.29                                    43.97  Rural  
4               12.26                                    44.68  Rural

In [38]:
df.duplicated().sum()

0

In [39]:
df.Frequency.value_counts()

Frequency
Monthly     381
 Monthly    359
Name: count, dtype: int64

**So let's also note that the Frequency column has no relevant because we can extract the months from our date column......so let's drop it**

In [40]:
df.drop('Frequency',axis=1,inplace=True)

In [41]:
df.head()

Region       Date  Estimated Unemployment Rate (%)  \
0  Andhra Pradesh 2019-05-31                             3.65   
1  Andhra Pradesh 2019-06-30                             3.05   
2  Andhra Pradesh 2019-07-31                             3.75   
3  Andhra Pradesh 2019-08-31                             3.32   
4  Andhra Pradesh 2019-09-30                             5.17   

   Estimated Employed  Estimated Labour Participation Rate (%)   Area  
0               12.00                                    43.24  Rural  
1               11.76                                    42.05  Rural  
2               12.09                                    43.50  Rural  
3               12.29                                    43.97  Rural  
4               12.26                                    44.68  Rural

**we want to do some Feature engineering.......So let's extract the month and year from the date column....**

In [42]:
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month_name()

df.head()

Region       Date  Estimated Unemployment Rate (%)  \
0  Andhra Pradesh 2019-05-31                             3.65   
1  Andhra Pradesh 2019-06-30                             3.05   
2  Andhra Pradesh 2019-07-31                             3.75   
3  Andhra Pradesh 2019-08-31                             3.32   
4  Andhra Pradesh 2019-09-30                             5.17   

   Estimated Employed  Estimated Labour Participation Rate (%)   Area  Year  \
0               12.00                                    43.24  Rural  2019   
1               11.76                                    42.05  Rural  2019   
2               12.09                                    43.50  Rural  2019   
3               12.29                                    43.97  Rural  2019   
4               12.26                                    44.68  Rural  2019   

       Month  
0        May  
1       June  
2       July  
3     August  
4  September

**Analyzing the Area Column**

In [43]:
df['Area'].value_counts()

Area
Urban    381
Rural    359
Name: count, dtype: int64

In [45]:
px.pie(df,names='Area',title='Count Plot of Area')

**Let's note that the Unemployment rate for Urban is slightly higher than the rural area**

In [46]:
df.Region.value_counts()

Region
Andhra Pradesh      28
Kerala              28
West Bengal         28
Uttar Pradesh       28
Tripura             28
Telangana           28
Tamil Nadu          28
Rajasthan           28
Punjab              28
Odisha              28
Madhya Pradesh      28
Maharashtra         28
Karnataka           28
Jharkhand           28
Himachal Pradesh    28
Haryana             28
Gujarat             28
Delhi               28
Chhattisgarh        28
Bihar               28
Meghalaya           27
Uttarakhand         27
Assam               26
Puducherry          26
Goa                 24
Jammu & Kashmir     21
Sikkim              17
Chandigarh          12
Name: count, dtype: int64

In [61]:
Region = df.groupby(['Region'])['Estimated Unemployment Rate (%)'].mean().reset_index()

Region

px.bar(Region,x='Region',y='Estimated Unemployment Rate (%)',title='Average Unemployment Rate by Region')

Region  Estimated Unemployment Rate (%)
0     Andhra Pradesh                         7.477143
1              Assam                         6.428077
2              Bihar                        18.918214
3         Chandigarh                        15.991667
4       Chhattisgarh                         9.240357
5              Delhi                        16.495357
6                Goa                         9.274167
7            Gujarat                         6.663929
8            Haryana                        26.283214
9   Himachal Pradesh                        18.540357
10   Jammu & Kashmir                        16.188571
11         Jharkhand                        20.585000
12         Karnataka                         6.676071
13            Kerala                        10.123929
14    Madhya Pradesh                         7.406429
15       Maharashtra                         7.557500
16         Meghalaya                         4.798889
17            Odisha                         5.657857
18        Puducherry                        10.215000
19            Punjab                        12.031071
20         Rajasthan                        14.058214
21            Sikkim                         7.249412
22        Tamil Nadu                         9.284286
23         Telangana                         7.737857
24           Tripura                        28.350357
25     Uttar Pradesh                        12.551429
26       Uttarakhand                         6.582963
27       West Bengal                         8.124643

In [79]:
px.bar(df,x='Region',y='Estimated Unemployment Rate (%)',title='Average Unemployment Rate by Region')

**This chart shows that the Tripura Region has the highest rate of unemployment in india next to Haryana region.**

In [62]:
df.head(1)

Region       Date  Estimated Unemployment Rate (%)  \
0  Andhra Pradesh 2019-05-31                             3.65   

   Estimated Employed  Estimated Labour Participation Rate (%)   Area  Year  \
0                12.0                                    43.24  Rural  2019   

  Month  
0   May

In [72]:
px.box(df, y='Estimated Unemployment Rate (%)',x= 'Year' ,title='Box Plot of Estimated Unemployment Rate vs year')

**There was sudden increase in the Unemployment Rate in 2020 due to the lockdown**

In [85]:
px.bar(df, y='Estimated Employed',x= 'Year', title = 'Estimated Employed vs Year')

**We can see that in 2020, the estimated employed is lower compared to year 2019....this is due to the covid**

In [77]:
px.bar(df, y='Estimated Labour Participation Rate (%)',x= 'Year', title= 'Labour participation vs year')

**We can also see that there is a high percentage of Labour Participation in the year 2019 as compared to 2020**

In [84]:
px.bar(df, y='Estimated Unemployment Rate (%)',x= 'Month', title= 'Unemployment Rate vs Month/year', color= 'Year')

**This chart shows that there was high rate of Unemployment in the 4th, 5th and 6th month in the year 2020**